### ISSUE TITLE
ncurses is not available in PHP7

### ISSUE THREAD

**Issue by ajrossnz** [TidalLabs/Slacker#20]
As crazy as it seems, apparently PHP7 does not have support for ncurses (yet):
https://groups.google.com/forum/#!topic/comp.lang.php/1EqPfC0_NGQ

When I try to install it via pecl, sure enough, the build fails. Apparently there is some bugfix that exists which isn't merged into the main trunk, but I don't know how to download it, far less install it into php7 on my Ubuntu box:
http://svn.php.net/viewvc/pecl/ncurses/trunk/ncurses.c?revision=340054&view=markup [bugfix]

I don't use PHP5, haven't in ages. Is there any way of using this awesome tool without downgrading? My tmux sessions have been waiting for this for a long time! ;)

**Comment by bkanber** [comment]
I just started working on a nodejs version of Slacker this morning (branch 'js' if you want to see 5 hours of progress -- channels and messages work but still no unread counts or oauth/token management yet). The PHP version will be removed because it's garbage ;P Gonna close this issue because of the move to node.

**Comment by bkanber** [comment]
See here https://github.com/bkanber/Slackadaisical for the nodejs version
